name: deploy-book

# Run this when the master or main branch changes
# 参考：https://jupyterbook.org/v1/publish/gh-pages.html
# あとこれも：https://docs.astral.sh/uv/guides/integration/github/

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.8"
          # enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build the book
        working-directory: transformer-textbook
        env:
          BASE_URL: https://NITIC-J-Murakami-Lab.github.io/transformer-textbook/
        run: uv run jupyter-book build --html

      - name: check files
        run: ls
        
      - name: check files
        run: ls ./transformer-textbook/_build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: transformer-textbook/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
